version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - rag_network

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./documents:/app/documents
    env_file:
      - .env
    depends_on:
      - qdrant
    networks:
      - rag_network
  postgres:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vectordb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rag_network
  
  langfuse:
    image: ghcr.io/langfuse/langfuse:sha-23150b6
    restart: always
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/vectordb
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: mysecret
      SALT: mysalt
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - rag_network
volumes:
  qdrant_data:
  postgres_data:

networks:
  rag_network:
    driver: bridge 